name: creacion-de-cursos

services:
  db:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - type: bind
        source: ./u170679010_fpptu.sql
        target: /docker-entrypoint-initdb.d/10-schema.sql
        read_only: true
      - type: bind
        source: ./docker/mysql/init/20-seed.sql
        target: /docker-entrypoint-initdb.d/20-seed.sql
        read_only: true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: prod
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PHP_TZ: ${PHP_TZ}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      app:
        condition: service_started
    ports:
      - "${APP_PORT}:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/health >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  # No phpMyAdmin in prod by default. If needed, enable explicitly and protect.

volumes:
  db_data:
    driver: local
